version: '3'

services:
  healthmonitor:
    build: .
    hostname: healthmonitor
    container_name: healthmonitor-service
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "/home/healthmonitor/server/db/"

